# -*- coding: utf-8 -*-
"""Untitled0 (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YAzk8BCA2hsGubardmNoxohXbXRyIbK3
"""

import tweepy
from textblob import TextBlob
from wordcloud import WordCloud
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

!pip install google_colab

import tweepy
from textblob import TextBlob
consumer_key='aX7DoZzgWnO5IpJcOYOpVMXLR'
consumer_key_secret='di9wJuQjOjVo5hI9ZqNEcvK3jNYwFSE4eBZm1cEaV7ySxpcUmn'
access_token='967898417354694657-W3m4WdC1prhhXhPdo4JDZzWEMZVdpnt'
access_token_secret='OgBafmubtoX6dCjPLyeu2ES5FRiGYc4WOJOVD0J1fpgeS'

auth= tweepy.OAuthHandler(consumer_key, consumer_key_secret)
auth.set_access_token(access_token, access_token_secret)

api=tweepy.API(auth)
public_tweets=api.search('Japanese Domestic Market')
for tweet in public_tweets:
  analysis=TextBlob(tweet.text)

  print("Sentiment is: \n")
  print(analysis.sentiment)